name: May24FASter
services:
  - name: web
    type: web
    ports:
      - port: 5000
        protocol: http
    build:
      commands:
        - apt-get update && apt-get install -y python3 python3-pip
        - python3 -m pip install --upgrade pip
        - python3 -m pip install -r requirements.txt
    run:
      command: gunicorn May24FASter:app --bind 0.0.0.0:5000
